import { useState, useMemo } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import ActivityCard from "components/ActivityCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Trackfit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative mx-5 grid grow grid-cols-3 gap-3">
        <div className="col-span-2 grid grid-flow-row-dense grid-cols-5 content-start gap-6 p-5 pt-8">
          <div className="col-span-5 flex w-full justify-between text-4xl text-neutral-300">
            <div>
              Welcome <span className="text-sky-300">Subhajit</span>
            </div>
            <div className="aspect-square h-full rounded-2xl border border-neutral-800 duration-200 hover:border-sky-300/50"></div>
          </div>
          {/* <div className="col-span-5 h-64 rounded-3xl bg-[#121212]"></div> */}

          <div className="col-span-5 grid grid-cols-4 gap-6">
            <div className="col-span-2 self-stretch rounded-3xl bg-[#121212]"></div>
            <div className="aspect-[4/5] self-stretch rounded-3xl bg-[#121212]"></div>
            <div className="aspect-[4/5] self-stretch rounded-3xl bg-[#121212]"></div>
          </div>

          <div className="col-span-3 row-span-1 flex gap-x-6 self-stretch">
            <div className="grow self-stretch rounded-3xl bg-[#121212]"></div>
            <div className="grow self-stretch rounded-3xl bg-[#121212]"></div>
          </div>

          <div className="col-span-3 row-span-1 self-stretch rounded-3xl bg-[#121212]"></div>

          <div className="col-span-2 row-span-2 h-48 rounded-3xl bg-[#121212]"></div>

          <div className="col-span-5 h-72 rounded-3xl bg-[#121212]"></div>
        </div>

        <div className="sticky top-0 col-span-1 grid h-screen py-5">
          <ActivityCard />
        </div>
      </div>
    </>
  );
}
