import { useState, useMemo } from "react";
import Head from "next/head";
import ActivityCard from "components/ActivityCard";
// import InputField from "components/Input";

export default function Workout() {
  const [name, setName] = useState<string>("");

  return (
    <>
      <Head>
        <title>Workout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative mx-5 grid grow grid-cols-3 gap-3">
        <div className="col-span-2 grid grid-flow-row-dense grid-cols-5 content-start gap-6 p-5 pt-8">
          <div className="col-span-5 flex w-full justify-between text-4xl text-neutral-300">
            <div>Workouts</div>
            <div className="aspect-square h-full rounded-2xl border border-neutral-800 duration-200 hover:border-sky-300/50"></div>
          </div>

          <div className="col-span-5 overflow-hidden rounded-2xl bg-[#121212]">
            <div className="flex p-3">
              <div className=" text-sm text-neutral-500">
                Saved Workouts Schedules
              </div>
            </div>
            <div className="flex flex-col divide-y divide-neutral-800 border-y border-neutral-800 p-3 text-neutral-400">
              <div className="">
                <div className="grid grid-cols-12">
                  <div className="col-span-6 text-lg">Leg Day Beginners</div>
                  <div></div>
                </div>
              </div>
            </div>
            <div className="flex justify-end px-3 py-1.5 text-xs text-neutral-500">
              No more workouts
            </div>
          </div>
        </div>

        <div className="sticky top-0 col-span-1 grid h-screen py-5">
          <ActivityCard />
        </div>
      </div>
    </>
  );
}
